[packages]
system = [
    "brightnessctl",
    "greetd-regreet",
    "greetd",
    "grimblast-git",
    "hypridle",
    "hyprland",
    "hyprlang",
    "hyprlock",
    "hyprpaper",
    "hyprpolkitagent",
    "hyprsunset",
    "kitty",
    "mako",
    "nautilus",
    "network-manager-applet",
    "uwsm",
    "wob",
    "wofi",
]

common = [
    "atuin",
    "bat",
    "direnv",
    "fish",
    "keychain",
    "lsd",
    "starship",
    "zoxide",
]
