[packages]
system = [
    "blueman",
    "bluez",
    "brightnessctl",
    "docker-buildx",
    "docker-compose",
    "docker",
    "gnome-calendar",
    "gnome-control-center",
    "gnome-keyring",
    "greetd-regreet",
    "greetd",
    "grimblast-git",          # add logic to download from aur on arch
    "hypridle",
    "hyprland",
    "hyprlang",
    "hyprlock",
    "hyprpaper",
    "hyprpolkitagent",
    "hyprsunset",
    "mako",
    "nautilus",
    "network-manager-applet",
    "pipewire-alsa",
    "pipewire-audio",
    "pipewire-pulse",
    "pipewire",
    "uwsm",
    "waybar",
    "wob",
    "wofi",
    "xsensors",
]

common = [
    "atuin",
    "bat",
    "btop",
    "direnv",
    "fish",
    "hyfetch",
    "keychain",
    "kitty",
    "lsd",
    "starship",
    "zoxide",
]

fonts = ["otf-firamono-nerd", "otf-font-awesome", "ttf-firacode-nerd"]
