[services]
user = [
    "hypridle.service",
    "hyprpaper.service",
    "hyprpolkitagent.service",
    "hyprsunset.service",
    "mako.service",
    "waybar.service",
]
system = ["docker.socket", "greetd"]
